### ISSUE TITLE
Initial Commit

### ISSUE THREAD

**Issue by sirthxalot** [sta-jek/starter#1]
# Summary

Yet we have an empty project, ready to get feed with some data. So lets begin to tackle down the default structure of our site, based on Jekyll. We have to build up everything from scratch but stick to the Jekyll Starter Template and HTML5 Boilerplate projects. In short we are going to create a very primitive version of our Jekyll Starter Template.

## Tasks

- [x] Add common project files.
- [x] Create a simple Jekyll starter template.
- [x] Define the default structure and add some common files.
- [x] Build the web files similar to the HTML5 Boilerplate.
- [x] Define Jekyll Gem dependencies in `_config.yml`.
- [x] Implement an advanced assets workflow and provide the default assets.
